#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
email = "christofer@nolander.me"
name = "Christofer Nolander"

[ui]
default-command = "log"
editor = "vim"


[aliases]
push = ["git", "push"]
fetch = ["git", "fetch"]
move = ["bookmark", "move"]
main = ["bookmark", "move", "main", "--to=@"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
